version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    
  web:
    container_name: ft_app
    build: .

    volumes:
      - .:/project
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:

    #! .env
    #! cont name
    #! cmd
    #! reqs file
    #! readme + .gitignore
    #! pycache ---
    # db - only
    # crud dir (+ __init__.py) - модуль
    # models, schemas