"""First migration

Revision ID: d532e1f29150
Revises: 
Create Date: 2022-10-19 14:37:28.587924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd532e1f29150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', postgresql.MONEY(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('upd_date', sa.Date(), nullable=True),
    sa.Column('is_onsale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Items')
    # ### end Alembic commands ###
